# Permalinks
permalink:           pretty

# Setup
title:               Matthew P. Ellis 
tagline:             Idea Guy
url:                 https://MatthewAwesome.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matthew Ellis
  url:               https://MatthewAwesome.github.io
  email:             matthew.p.ellis23@gmail.com
  github_username:   MatthewAwesome
  insta_username:    Matthew.Awesome.23
  linkedin_username: matthewawesome
  facebook_username: matthew.awesome.23

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/MatthewAwesome/MatthewAwesome.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
