# site settings
title: Matthew Ellis
subtitle: Founder and Idea Guy
email: matthew.p.ellis23@gmail.com
description: Interdiscplinary innovator. Founder of Alzheimers disease startup: Neuroptica. Sometimes a writer. Always a thinker.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Matthew Ellis
image: ""
projectsURL: "#one"


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url: #http://www.facebook.com/matthew.awesome.23
github_url: https://github.com/MatthewAwesome/
instagram_url: https://instagram.com/Matthew.Awesome.23
linkedin_url: https://www.linkedin.com/in/awesomeideas
pinterest_url:
twitter_url: https://twitter.com/MatthewEllis23
email: matthew.p.ellis23@gmail.com

# build settings
markdown: kramdown
sass:
  style: compressed
